#!/bin/bash
clear
echo ""
echo ""
echo ""
read -p " Username : " username
grep -E "^$username" /etc/ppp/chap-secrets >/dev/null
if [ $? -eq 0 ]; then
echo "USERNAME นี้ มีแล้ว"
exit 0
else
read -p " PASSWORD : " password
read -p " กำหนดวัน " masa_aktif

today=`date +%s`
masa_aktif_detik=$(( $masa_aktif * 86400 ))
saat_expired=$(($today + $masa_aktif_detik))
tanggal_expired=$(date -u --date="1970-01-01 $saat_expired sec GMT" +%Y/%m/%d)
tanggal_expired_display=$(date -u --date="1970-01-01 $saat_expired sec GMT" '+%d %B %Y')
clear

echo "Creating Username: $username"
sleep 0.2
echo "Creating Password: $username"
sleep 0.3
MYIP=$(wget -qO- ipv4.icanhazip.com)
echo "$username	*	$password	*" >> /etc/ppp/chap-secrets
echo "$username *   $password   *  $saat_expired"  >> /var/lib/premium-script/data-user-pptp
 clear
echo ""
echo ""
echo -e "                  \033[38;5;255m\033[48;5;234m\033[1m > O C S P A N E L - V P N ™ <   \033[0m"
echo -e "              \033[1;38;48m ======================================= \033[0m"
echo ""
echo -e "                      \033[38;5;255m\033[48;5;234m\033[1m > P P T P - V P N <    \033[0m"
echo ""
echo -e "              \033[1;38;48m ======================================= \033[0m"
echo ""
echo -e "                   \033[38;5;255m\033[48;5;234m\033[1m 📊 HOST   : $MYIP  📊    \033[0m"
echo -e "                      \033[38;5;255m\033[48;5;234m\033[1m 📊 USERNAME    : $username  📊    \033[0m"
echo -e "                      \033[38;5;255m\033[48;5;234m\033[1m 📊 PASSWORD    : $password  📊    \033[0m"
echo -e "                 \033[38;5;255m\033[48;5;234m\033[1m 📊 EXP DAY : $tanggal_expired_display  📊    \033[0m"
echo ""
echo -e "              \033[1;38;48m ======================================= \033[0m"
echo " "
fi
